In [1]:
# -----------------------------
# Imports
# -----------------------------
from pathlib import Path
import re
import pandas as pd
import numpy as np

# Display settings for easier inspection
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_colwidth", None)

# -----------------------------
# Paths
# -----------------------------
REPO_ROOT = Path("..").resolve()
DATA_RAW = REPO_ROOT / "data" / "raw"
DATA_PROCESSED = REPO_ROOT / "data" / "processed"


DEMO_JOBS_FILE = "job_descriptions.csv"

print("REPO_ROOT:", REPO_ROOT)
print("Raw file path:", DATA_RAW / DEMO_JOBS_FILE)
print("Processed folder:", DATA_PROCESSED)

REPO_ROOT: C:\Users\COMPUTER CARE\aeej1\JobPlatform
Raw file path: C:\Users\COMPUTER CARE\aeej1\JobPlatform\data\raw\job_descriptions.csv
Processed folder: C:\Users\COMPUTER CARE\aeej1\JobPlatform\data\processed

In [2]:
# -----------------------------
# Read only the header first to inspect the actual column names.
# -----------------------------
raw_columns = pd.read_csv(DATA_RAW / DEMO_JOBS_FILE, nrows=0).columns.tolist()

print("Raw columns found in CSV:")
print(raw_columns)

Raw columns found in CSV:
['Job Id', 'Experience', 'Qualifications', 'Salary Range', 'location', 'Country', 'latitude', 'longitude', 'Work Type', 'Company Size', 'Job Posting Date', 'Preference', 'Contact Person', 'Contact', 'Job Title', 'Role', 'Job Portal', 'Job Description', 'Benefits', 'skills', 'Responsibilities', 'Company', 'Company Profile']

In [3]:
# -----------------------------
# Map actual CSV headers intointernal names.
#
# 
# -----------------------------
COLUMN_MAPPING = {}

for col in raw_columns:
    c = col.strip().lower()

    if c == "job id":
        COLUMN_MAPPING[col] = "job_id"
    elif c == "experience":
        COLUMN_MAPPING[col] = "experience"
    elif c == "qualifications":
        COLUMN_MAPPING[col] = "qualifications"
    elif c == "location":
        COLUMN_MAPPING[col] = "location"
    elif c == "country":
        COLUMN_MAPPING[col] = "country"
    elif c == "salary range":
        COLUMN_MAPPING[col] = "salary_range"
    elif c == "work type":
        COLUMN_MAPPING[col] = "work_type"
    elif c == "job posting date":
        COLUMN_MAPPING[col] = "job_posting_date"
    elif c == "job title":
        COLUMN_MAPPING[col] = "job_title"
    elif c == "role":
        COLUMN_MAPPING[col] = "role"
    elif c == "job portal":
        COLUMN_MAPPING[col] = "job_portal"
    elif c == "job description":
        COLUMN_MAPPING[col] = "job_description"
    elif c == "benefits":
        COLUMN_MAPPING[col] = "benefits"
    elif c == "skills":
        COLUMN_MAPPING[col] = "skills"
    elif c == "responsibilities":
        COLUMN_MAPPING[col] = "responsibilities"
    elif c in ["company name", "company"]:
        COLUMN_MAPPING[col] = "company_name"
    elif c == "company profile":
        COLUMN_MAPPING[col] = "company_profile"

print("Detected mapping:")
print(COLUMN_MAPPING)

Detected mapping:
{'Job Id': 'job_id', 'Experience': 'experience', 'Qualifications': 'qualifications', 'Salary Range': 'salary_range', 'location': 'location', 'Country': 'country', 'Work Type': 'work_type', 'Job Posting Date': 'job_posting_date', 'Job Title': 'job_title', 'Role': 'role', 'Job Portal': 'job_portal', 'Job Description': 'job_description', 'Benefits': 'benefits', 'skills': 'skills', 'Responsibilities': 'responsibilities', 'Company': 'company_name', 'Company Profile': 'company_profile'}

In [4]:
# -----------------------------
# Load only the mapped columns from the large CSV
# to keep memory usage lower
# -----------------------------
use_columns = list(COLUMN_MAPPING.keys())

demo_jobs_raw = pd.read_csv(
    DATA_RAW / DEMO_JOBS_FILE,
    usecols=use_columns
)

print("Loaded shape:", demo_jobs_raw.shape)
print("Loaded columns:", demo_jobs_raw.columns.tolist())

display(demo_jobs_raw.head(3))

Loaded shape: (1615940, 17)
Loaded columns: ['Job Id', 'Experience', 'Qualifications', 'Salary Range', 'location', 'Country', 'Work Type', 'Job Posting Date', 'Job Title', 'Role', 'Job Portal', 'Job Description', 'Benefits', 'skills', 'Responsibilities', 'Company', 'Company Profile']

,Job Id,Experience,Qualifications,Salary Range,location,Country,Work Type,Job Posting Date,Job Title,Role,Job Portal,Job Description,Benefits,skills,Responsibilities,Company,Company Profile
0,1089843540111562,5 to 15 Years,M.Tech,$59K-$99K,Douglas,Isle of Man,Intern,2022-04-24,Digital Marketing Specialist,Social Media Manager,Snagajob,"Social Media Managers oversee an organizations social media presence. They create and schedule content, engage with followers, and analyze social media metrics to drive brand awareness and engagement.","{'Flexible Spending Accounts (FSAs), Relocation Assistance, Legal Assistance, Employee Recognition Programs, Financial Counseling'}","Social media platforms (e.g., Facebook, Twitter, Instagram) Content creation and scheduling Social media analytics and insights Community engagement Paid social advertising","Manage and grow social media accounts, create engaging content, and interact with the online community. Develop social media content calendars and strategies. Monitor social media trends and engagement metrics.",Icahn Enterprises,"{""Sector"":""Diversified"",""Industry"":""Diversified Financials"",""City"":""Sunny Isles Beach"",""State"":""Florida"",""Zip"":""33160"",""Website"":""www.ielp.com"",""Ticker"":""IEP"",""CEO"":""David Willetts""}"
1,398454096642776,2 to 12 Years,BCA,$56K-$116K,Ashgabat,Turkmenistan,Intern,2022-12-19,Web Developer,Frontend Web Developer,Idealist,"Frontend Web Developers design and implement user interfaces for websites, ensuring they are visually appealing and user-friendly. They collaborate with designers and backend developers to create seamless web experiences for users.","{'Health Insurance, Retirement Plans, Paid Time Off (PTO), Flexible Work Arrangements, Employee Assistance Programs (EAP)'}","HTML, CSS, JavaScript Frontend frameworks (e.g., React, Angular) User experience (UX)","Design and code user interfaces for websites, ensuring a seamless and visually appealing user experience. Collaborate with UX designers to optimize user journeys. Ensure cross-browser compatibility and responsive design.",PNC Financial Services Group,"{""Sector"":""Financial Services"",""Industry"":""Commercial Banks"",""City"":""Pittsburgh"",""State"":""Pennsylvania"",""Zip"":""15222"",""Website"":""www.pnc.com"",""Ticker"":""PNC"",""CEO"":""William S. Demchak""}"
2,481640072963533,0 to 12 Years,PhD,$61K-$104K,Macao,"Macao SAR, China",Temporary,2022-09-14,Operations Manager,Quality Control Manager,Jobs2Careers,"Quality Control Managers establish and enforce quality standards within an organization. They develop quality control processes, perform inspections, and implement corrective actions to maintain product or service quality.","{'Legal Assistance, Bonuses and Incentive Programs, Wellness Programs, Employee Discounts, Retirement Plans'}","Quality control processes and methodologies Statistical process control (SPC) Root cause analysis and corrective action Quality management systems (e.g., ISO 9001) Compliance and regulatory knowledge",Establish and enforce quality control standards and procedures. Conduct quality audits and inspections. Collaborate with production teams to address quality issues and implement improvements.,United Services Automobile Assn.,"{""Sector"":""Insurance"",""Industry"":""Insurance: Property and Casualty (Stock)"",""City"":""San Antonio"",""State"":""Texas"",""Zip"":""78288"",""Website"":""www.usaa.com"",""Ticker"":"""",""CEO"":""Wayne Peacock""}"

In [5]:
# -----------------------------
# Rename raw columns into stable snake_case names
# -----------------------------
demo_jobs = demo_jobs_raw.rename(columns=COLUMN_MAPPING).copy()

print("Columns after rename:")
print(demo_jobs.columns.tolist())

display(demo_jobs.head(3))

Columns after rename:
['job_id', 'experience', 'qualifications', 'salary_range', 'location', 'country', 'work_type', 'job_posting_date', 'job_title', 'role', 'job_portal', 'job_description', 'benefits', 'skills', 'responsibilities', 'company_name', 'company_profile']

,job_id,experience,qualifications,salary_range,location,country,work_type,job_posting_date,job_title,role,job_portal,job_description,benefits,skills,responsibilities,company_name,company_profile
0,1089843540111562,5 to 15 Years,M.Tech,$59K-$99K,Douglas,Isle of Man,Intern,2022-04-24,Digital Marketing Specialist,Social Media Manager,Snagajob,"Social Media Managers oversee an organizations social media presence. They create and schedule content, engage with followers, and analyze social media metrics to drive brand awareness and engagement.","{'Flexible Spending Accounts (FSAs), Relocation Assistance, Legal Assistance, Employee Recognition Programs, Financial Counseling'}","Social media platforms (e.g., Facebook, Twitter, Instagram) Content creation and scheduling Social media analytics and insights Community engagement Paid social advertising","Manage and grow social media accounts, create engaging content, and interact with the online community. Develop social media content calendars and strategies. Monitor social media trends and engagement metrics.",Icahn Enterprises,"{""Sector"":""Diversified"",""Industry"":""Diversified Financials"",""City"":""Sunny Isles Beach"",""State"":""Florida"",""Zip"":""33160"",""Website"":""www.ielp.com"",""Ticker"":""IEP"",""CEO"":""David Willetts""}"
1,398454096642776,2 to 12 Years,BCA,$56K-$116K,Ashgabat,Turkmenistan,Intern,2022-12-19,Web Developer,Frontend Web Developer,Idealist,"Frontend Web Developers design and implement user interfaces for websites, ensuring they are visually appealing and user-friendly. They collaborate with designers and backend developers to create seamless web experiences for users.","{'Health Insurance, Retirement Plans, Paid Time Off (PTO), Flexible Work Arrangements, Employee Assistance Programs (EAP)'}","HTML, CSS, JavaScript Frontend frameworks (e.g., React, Angular) User experience (UX)","Design and code user interfaces for websites, ensuring a seamless and visually appealing user experience. Collaborate with UX designers to optimize user journeys. Ensure cross-browser compatibility and responsive design.",PNC Financial Services Group,"{""Sector"":""Financial Services"",""Industry"":""Commercial Banks"",""City"":""Pittsburgh"",""State"":""Pennsylvania"",""Zip"":""15222"",""Website"":""www.pnc.com"",""Ticker"":""PNC"",""CEO"":""William S. Demchak""}"
2,481640072963533,0 to 12 Years,PhD,$61K-$104K,Macao,"Macao SAR, China",Temporary,2022-09-14,Operations Manager,Quality Control Manager,Jobs2Careers,"Quality Control Managers establish and enforce quality standards within an organization. They develop quality control processes, perform inspections, and implement corrective actions to maintain product or service quality.","{'Legal Assistance, Bonuses and Incentive Programs, Wellness Programs, Employee Discounts, Retirement Plans'}","Quality control processes and methodologies Statistical process control (SPC) Root cause analysis and corrective action Quality management systems (e.g., ISO 9001) Compliance and regulatory knowledge",Establish and enforce quality control standards and procedures. Conduct quality audits and inspections. Collaborate with production teams to address quality issues and implement improvements.,United Services Automobile Assn.,"{""Sector"":""Insurance"",""Industry"":""Insurance: Property and Casualty (Stock)"",""City"":""San Antonio"",""State"":""Texas"",""Zip"":""78288"",""Website"":""www.usaa.com"",""Ticker"":"""",""CEO"":""Wayne Peacock""}"

In [6]:
# -----------------------------
# Ensuring required columns exist.
#
# Important:
# - keep raw role if it exists
# - only create empty role if the column is truly absent
# - do NOT overwrite role with job_title here
# -----------------------------
REQUIRED_COLUMNS = [
    "job_id",
    "experience",
    "qualifications",
    "location",
    "salary_range",
    "country",
    "work_type",
    "job_posting_date",
    "job_title",
    "role",
    "job_portal",
    "job_description",
    "benefits",
    "skills",
    "responsibilities",
    "company_name",
    "company_profile",
]

for col in REQUIRED_COLUMNS:
    if col not in demo_jobs.columns:
        demo_jobs[col] = ""

print("Columns after schema check:")
print(demo_jobs.columns.tolist())

display(demo_jobs[["job_title", "role", "skills"]].head(5))

Columns after schema check:
['job_id', 'experience', 'qualifications', 'salary_range', 'location', 'country', 'work_type', 'job_posting_date', 'job_title', 'role', 'job_portal', 'job_description', 'benefits', 'skills', 'responsibilities', 'company_name', 'company_profile']

,job_title,role,skills
0,Digital Marketing Specialist,Social Media Manager,"Social media platforms (e.g., Facebook, Twitter, Instagram) Content creation and scheduling Social media analytics and insights Community engagement Paid social advertising"
1,Web Developer,Frontend Web Developer,"HTML, CSS, JavaScript Frontend frameworks (e.g., React, Angular) User experience (UX)"
2,Operations Manager,Quality Control Manager,"Quality control processes and methodologies Statistical process control (SPC) Root cause analysis and corrective action Quality management systems (e.g., ISO 9001) Compliance and regulatory knowledge"
3,Network Engineer,Wireless Network Engineer,Wireless network design and architecture Wi-Fi standards and protocols RF (Radio Frequency) planning and optimization Wireless security protocols Troubleshooting wireless network issues
4,Event Manager,Conference Manager,Event planning Conference logistics Budget management Vendor coordination Marketing and promotion Client relations

In [7]:
# -----------------------------
# Basic text cleaning
# -----------------------------
def clean_text(x):
    if pd.isna(x):
        return ""

    s = str(x)
    s = s.replace("\u00a0", " ")
    s = re.sub(r"\s+", " ", s)
    return s.strip()

In [8]:
# -----------------------------
# Clean important text columns lightly.
# -----------------------------
TEXT_COLUMNS = [
    "experience",
    "qualifications",
    "location",
    "salary_range",
    "country",
    "work_type",
    "job_posting_date",
    "job_title",
    "role",
    "job_portal",
    "job_description",
    "benefits",
    "skills",
    "responsibilities",
    "company_name",
    "company_profile",
]

for col in TEXT_COLUMNS:
    demo_jobs[col] = demo_jobs[col].apply(clean_text)

display(demo_jobs[["job_title", "role", "skills"]].head(5))

,job_title,role,skills
0,Digital Marketing Specialist,Social Media Manager,"Social media platforms (e.g., Facebook, Twitter, Instagram) Content creation and scheduling Social media analytics and insights Community engagement Paid social advertising"
1,Web Developer,Frontend Web Developer,"HTML, CSS, JavaScript Frontend frameworks (e.g., React, Angular) User experience (UX)"
2,Operations Manager,Quality Control Manager,"Quality control processes and methodologies Statistical process control (SPC) Root cause analysis and corrective action Quality management systems (e.g., ISO 9001) Compliance and regulatory knowledge"
3,Network Engineer,Wireless Network Engineer,Wireless network design and architecture Wi-Fi standards and protocols RF (Radio Frequency) planning and optimization Wireless security protocols Troubleshooting wireless network issues
4,Event Manager,Conference Manager,Event planning Conference logistics Budget management Vendor coordination Marketing and promotion Client relations

In [9]:
# -----------------------------
# Inspect whether role and job_title differ in the dataset.
# This confirms whether role is meaningful enough to preserve.
# -----------------------------
role_title_check = demo_jobs[["job_title", "role"]].copy()
role_title_check["same_value"] = (
    role_title_check["job_title"].str.lower() == role_title_check["role"].str.lower()
)

print("Rows where role == job_title:", int(role_title_check["same_value"].sum()))
print("Total rows:", len(role_title_check))

display(role_title_check.head(10))

Rows where role == job_title: 0
Total rows: 1615940

                      job_title                       role  same_value
0  Digital Marketing Specialist       Social Media Manager       False
1                 Web Developer     Frontend Web Developer       False
2            Operations Manager    Quality Control Manager       False
3              Network Engineer  Wireless Network Engineer       False
4                 Event Manager         Conference Manager       False
5               Software Tester  Quality Assurance Analyst       False
6                       Teacher          Classroom Teacher       False
7                UX/UI Designer    User Interface Designer       False
8                UX/UI Designer       Interaction Designer       False
9               Wedding Planner         Wedding Consultant       False

In [10]:
# -----------------------------
# Building simple quality signals for filtering
# -----------------------------
demo_jobs["description_len"] = demo_jobs["job_description"].str.len()
demo_jobs["skills_len"] = demo_jobs["skills"].str.len()
demo_jobs["responsibilities_len"] = demo_jobs["responsibilities"].str.len()

demo_jobs["quality_score"] = (
    demo_jobs["description_len"].fillna(0)
    + demo_jobs["skills_len"].fillna(0)
    + demo_jobs["responsibilities_len"].fillna(0)
)

display(
    demo_jobs[[
        "job_title",
        "role",
        "company_name",
        "description_len",
        "skills_len",
        "responsibilities_len",
        "quality_score"
    ]].head(5)
)

,job_title,role,company_name,description_len,skills_len,responsibilities_len,quality_score
0,Digital Marketing Specialist,Social Media Manager,Icahn Enterprises,200,172,210,582
1,Web Developer,Frontend Web Developer,PNC Financial Services Group,231,85,220,536
2,Operations Manager,Quality Control Manager,United Services Automobile Assn.,222,199,191,612
3,Network Engineer,Wireless Network Engineer,Hess,200,185,186,571
4,Event Manager,Conference Manager,Cairn Energy,235,114,158,507

In [11]:
# -----------------------------
# Keeping rows that are strong enough for the demo.
# -----------------------------
filtered_jobs = demo_jobs[
    (demo_jobs["job_title"] != "") &
    (demo_jobs["company_name"] != "") &
    (demo_jobs["location"] != "") &
    (demo_jobs["job_description"] != "") &
    (demo_jobs["description_len"] >= 200) &
    (
        (demo_jobs["skills_len"] >= 10) |
        (demo_jobs["responsibilities_len"] >= 40)
    )
].copy()

print("Original rows:", len(demo_jobs))
print("After filtering:", len(filtered_jobs))

display(filtered_jobs.head(3))

Original rows: 1615940
After filtering: 549156

,job_id,experience,qualifications,salary_range,location,country,work_type,job_posting_date,job_title,role,job_portal,job_description,benefits,skills,responsibilities,company_name,company_profile,description_len,skills_len,responsibilities_len,quality_score
0,1089843540111562,5 to 15 Years,M.Tech,$59K-$99K,Douglas,Isle of Man,Intern,2022-04-24,Digital Marketing Specialist,Social Media Manager,Snagajob,"Social Media Managers oversee an organizations social media presence. They create and schedule content, engage with followers, and analyze social media metrics to drive brand awareness and engagement.","{'Flexible Spending Accounts (FSAs), Relocation Assistance, Legal Assistance, Employee Recognition Programs, Financial Counseling'}","Social media platforms (e.g., Facebook, Twitter, Instagram) Content creation and scheduling Social media analytics and insights Community engagement Paid social advertising","Manage and grow social media accounts, create engaging content, and interact with the online community. Develop social media content calendars and strategies. Monitor social media trends and engagement metrics.",Icahn Enterprises,"{""Sector"":""Diversified"",""Industry"":""Diversified Financials"",""City"":""Sunny Isles Beach"",""State"":""Florida"",""Zip"":""33160"",""Website"":""www.ielp.com"",""Ticker"":""IEP"",""CEO"":""David Willetts""}",200,172,210,582
1,398454096642776,2 to 12 Years,BCA,$56K-$116K,Ashgabat,Turkmenistan,Intern,2022-12-19,Web Developer,Frontend Web Developer,Idealist,"Frontend Web Developers design and implement user interfaces for websites, ensuring they are visually appealing and user-friendly. They collaborate with designers and backend developers to create seamless web experiences for users.","{'Health Insurance, Retirement Plans, Paid Time Off (PTO), Flexible Work Arrangements, Employee Assistance Programs (EAP)'}","HTML, CSS, JavaScript Frontend frameworks (e.g., React, Angular) User experience (UX)","Design and code user interfaces for websites, ensuring a seamless and visually appealing user experience. Collaborate with UX designers to optimize user journeys. Ensure cross-browser compatibility and responsive design.",PNC Financial Services Group,"{""Sector"":""Financial Services"",""Industry"":""Commercial Banks"",""City"":""Pittsburgh"",""State"":""Pennsylvania"",""Zip"":""15222"",""Website"":""www.pnc.com"",""Ticker"":""PNC"",""CEO"":""William S. Demchak""}",231,85,220,536
2,481640072963533,0 to 12 Years,PhD,$61K-$104K,Macao,"Macao SAR, China",Temporary,2022-09-14,Operations Manager,Quality Control Manager,Jobs2Careers,"Quality Control Managers establish and enforce quality standards within an organization. They develop quality control processes, perform inspections, and implement corrective actions to maintain product or service quality.","{'Legal Assistance, Bonuses and Incentive Programs, Wellness Programs, Employee Discounts, Retirement Plans'}","Quality control processes and methodologies Statistical process control (SPC) Root cause analysis and corrective action Quality management systems (e.g., ISO 9001) Compliance and regulatory knowledge",Establish and enforce quality control standards and procedures. Conduct quality audits and inspections. Collaborate with production teams to address quality issues and implement improvements.,United Services Automobile Assn.,"{""Sector"":""Insurance"",""Industry"":""Insurance: Property and Casualty (Stock)"",""City"":""San Antonio"",""State"":""Texas"",""Zip"":""78288"",""Website"":""www.usaa.com"",""Ticker"":"""",""CEO"":""Wayne Peacock""}",222,199,191,612

In [12]:
# -----------------------------
# Remove obvious duplicates using:
# - role
# - job title
# - company
# - location
# - first part of description
# -----------------------------
filtered_jobs["dup_key"] = (
    filtered_jobs["role"].str.lower() + " | " +
    filtered_jobs["job_title"].str.lower() + " | " +
    filtered_jobs["company_name"].str.lower() + " | " +
    filtered_jobs["location"].str.lower() + " | " +
    filtered_jobs["job_description"].str.lower().str[:200]
)

before_dedup = len(filtered_jobs)
filtered_jobs = filtered_jobs.drop_duplicates(subset=["dup_key"]).copy()
after_dedup = len(filtered_jobs)

print("Before dedup:", before_dedup)
print("After dedup:", after_dedup)

Before dedup: 549156
After dedup: 541207

In [13]:
# -----------------------------
# Inspect diversity.
#
# Prefer role if populated; otherwise job_title is still available.
# -----------------------------
print("Top roles:")
display(filtered_jobs["role"].value_counts().head(20))

print("\nTop job titles:")
display(filtered_jobs["job_title"].value_counts().head(20))

print("\nTop work types:")
display(filtered_jobs["work_type"].value_counts().head(10))

Top roles:

role
User Interface Designer          13553
Social Media Manager             13446
User Experience Designer         13441
Social Media Analyst             10371
SEO Specialist                   10232
Backend Developer                10155
Office Manager                   10087
Customer Success Manager         10053
Frontend Developer               10024
Account Executive                 6924
Inside Sales Representative       6905
Personal Assistant                6901
Training Coordinator              6900
Data Scientist                    6861
IT Project Manager                6850
Business Intelligence Analyst     6835
Product Marketing Manager         6820
DevOps Engineer                   6812
Supply Chain Manager              6802
Benefits Coordinator              6734
Name: count, dtype: int64

Top job titles:

job_title
Digital Marketing Specialist    27156
UX/UI Designer                  26994
Software Engineer               26991
Sales Representative            17339
Social Media Manager            17255
Data Analyst                    17121
HR Coordinator                  16997
Executive Assistant             16988
Customer Support Specialist     16936
Operations Manager              13743
Project Manager                 13735
Marketing Manager               13718
Graphic Designer                13709
Marketing Specialist            10527
Java Developer                  10500
Pediatrician                    10439
Quality Assurance Analyst       10434
Accountant                      10425
Legal Advisor                   10417
QA Analyst                      10409
Name: count, dtype: int64

Top work types:

work_type
Temporary    108667
Part-Time    108638
Contract     108081
Intern       108071
Full-Time    107750
Name: count, dtype: int64

In [14]:
# -----------------------------
# Build balanced subset.
#
# We sample by role, but if role is blank for some rows,
# we create a temporary sampling label from job_title.
# -----------------------------
filtered_jobs["sampling_label"] = filtered_jobs["role"].replace("", np.nan)
filtered_jobs["sampling_label"] = filtered_jobs["sampling_label"].fillna(filtered_jobs["job_title"])

MAX_PER_ROLE = 80

balanced_subset = (
    filtered_jobs
    .groupby("sampling_label", group_keys=False)
    .apply(lambda x: x.sample(n=min(len(x), MAX_PER_ROLE), random_state=42))
    .reset_index(drop=True)
)

print("Balanced subset size:", len(balanced_subset))
print("Balanced subset columns:")
print(balanced_subset.columns.tolist())

display(balanced_subset.head(3))

Balanced subset size: 9920
Balanced subset columns:
['job_id', 'experience', 'qualifications', 'salary_range', 'location', 'country', 'work_type', 'job_posting_date', 'job_title', 'role', 'job_portal', 'job_description', 'benefits', 'skills', 'responsibilities', 'company_name', 'company_profile', 'description_len', 'skills_len', 'responsibilities_len', 'quality_score', 'dup_key']

,job_id,experience,qualifications,salary_range,location,country,work_type,job_posting_date,job_title,role,job_portal,job_description,benefits,skills,responsibilities,company_name,company_profile,description_len,skills_len,responsibilities_len,quality_score,dup_key
0,692765415301241,2 to 11 Years,B.Com,$65K-$90K,Minsk,Belarus,Contract,2023-05-13,Sales Representative,Account Executive,LinkedIn,"Account Executives manage and grow relationships with existing clients or customers. They understand client needs, propose solutions, negotiate contracts, and ensure customer satisfaction, often working closely with sales and customer support teams.","{'Tuition Reimbursement, Stock Options or Equity Grants, Parental Leave, Wellness Programs, Childcare Assistance'}",Sales strategy and planning Account management Customer relationship management Solution selling Sales forecasting Contract negotiation Sales metrics and reporting,"Manage client accounts, negotiate contracts, and achieve revenue targets by selling products or services. Provide ongoing support and solutions to clients. Collaborate with cross-functional teams to meet client needs.",VMware,"{""Sector"":""Software"",""Industry"":""Computer Software"",""City"":""Palo Alto"",""State"":""California"",""Zip"":""94304"",""Website"":""www.vmware.com"",""Ticker"":""VMW"",""CEO"":""Raghu Raghuram""}",249,163,217,629,"account executive | sales representative | vmware | minsk | account executives manage and grow relationships with existing clients or customers. they understand client needs, propose solutions, negotiate contracts, and ensure customer satisfaction, often worki"
1,370087477853353,0 to 12 Years,B.Com,$56K-$100K,Berlin,Germany,Temporary,2023-05-31,Sales Representative,Account Executive,Glassdoor,"Account Executives manage and grow relationships with existing clients or customers. They understand client needs, propose solutions, negotiate contracts, and ensure customer satisfaction, often working closely with sales and customer support teams.","{'Employee Assistance Programs (EAP), Tuition Reimbursement, Profit-Sharing, Transportation Benefits, Parental Leave'}",Sales strategy and planning Account management Customer relationship management Solution selling Sales forecasting Contract negotiation Sales metrics and reporting,"Manage client accounts, negotiate contracts, and achieve revenue targets by selling products or services. Provide ongoing support and solutions to clients. Collaborate with cross-functional teams to meet client needs.",Continental AG,"{""Sector"":""Automotive"",""Industry"":""Automotive"",""City"":""Hanover"",""State"":""N/A"",""Zip"":""N/A"",""Website"":""www.continental-corporation.com"",""Ticker"":""CON"",""CEO"":""Nikolai Setzer""}",249,163,217,629,"account executive | sales representative | continental ag | berlin | account executives manage and grow relationships with existing clients or customers. they understand client needs, propose solutions, negotiate contracts, and ensure customer satisfaction, often worki"
2,862414233805803,4 to 9 Years,BA,$58K-$103K,Saint George's,Grenada,Temporary,2022-06-25,Sales Representative,Account Executive,Jobs2Careers,"Account Executives manage and grow relationships with existing clients or customers. They understand client needs, propose solutions, negotiate contracts, and ensure customer satisfaction, often working closely with sales and customer support teams.","{'Transportation Benefits, Professional Development, Bonuses and Incentive Programs, Profit-Sharing, Employee Discounts'}",Sales strategy and planning Account management Customer relationship management Solution selling Sales forecasting Contract negotiation Sales metrics and reporting,"Manage client accounts, negotiate contracts, and achieve revenue targets by selling products or services. Provide ongoing support and solutions to clients. Collaborate with cross-functional teams to meet client needs.",IBM (International Business Machines Corporation),"{""Sector"":""Technology/IT Services"",""Industry"":""Technology"",""City"":""Armonk"",""State"":""NY"",""Zip"":""10504"",""Website"":""https://www.ibm.com/"",""Ticker"":""IBM"",""CEO"":""Arvind Krishna""}",249,163,217,629,"account executive | sales representative | ibm (international business machines corporation) | saint george's | account executives manage and grow relationships with existing clients or customers. they understand client needs, propose solutions, negotiate contracts, and ensure customer satisfaction, often worki"

In [15]:
# -----------------------------
# Applying final cap if needed
# -----------------------------
TARGET_SIZE = 5000

if len(balanced_subset) > TARGET_SIZE:
    demo_subset = balanced_subset.sample(n=TARGET_SIZE, random_state=42).copy()
else:
    demo_subset = balanced_subset.copy()

print("Final demo subset size:", len(demo_subset))

Final demo subset size: 5000

In [16]:
# -----------------------------
# Keep only the columns needed for Notebook 9.
# Drop helper columns used only for filtering/sampling.
# -----------------------------
FINAL_SUBSET_COLUMNS = [
    "job_id",
    "experience",
    "qualifications",
    "location",
    "salary_range",
    "country",
    "work_type",
    "job_posting_date",
    "job_title",
    "role",
    "job_portal",
    "job_description",
    "benefits",
    "skills",
    "responsibilities",
    "company_name",
    "company_profile",
]

demo_subset = demo_subset[FINAL_SUBSET_COLUMNS].copy()

print("Final subset columns:")
print(demo_subset.columns.tolist())

display(demo_subset[["job_title", "role", "skills"]].head(10))

Final subset columns:
['job_id', 'experience', 'qualifications', 'location', 'salary_range', 'country', 'work_type', 'job_posting_date', 'job_title', 'role', 'job_portal', 'job_description', 'benefits', 'skills', 'responsibilities', 'company_name', 'company_profile']

,job_title,role,skills
5268,Java Developer,Java Software Engineer,"Java programming Java frameworks (e.g., Spring) Object-oriented design Code debugging Software development Problem-solving skills"
510,Architectural Designer,Architectural Drafter,Architectural drafting AutoCAD 2D and 3D modeling Blueprint reading Building codes Collaboration with architects Detail-oriented
4328,Business Analyst,Healthcare Business Analyst,Healthcare industry knowledge Health data analysis HIPAA regulations EMR systems
8379,QA Analyst,Software QA Tester,"Software quality assurance Test planning Test case design Test execution Defect tracking Test automation (e.g., Selenium)"
7803,Sales Consultant,Sales Trainer,Sales training Sales coaching Training program development Sales techniques Product knowledge Presentation skills
8641,Systems Engineer,Systems Integration Specialist,Systems integration Integration architecture Data mapping Middleware technologies API integration System testing Troubleshooting
8523,Environmental Consultant,Sustainability Consultant,Sustainability consulting Sustainability assessments Sustainable practices Green building standards Environmental policies Client communication
3971,Web Developer,Frontend Web Developer,"HTML, CSS, JavaScript Frontend frameworks (e.g., React, Angular) User experience (UX)"
9180,Customer Support Specialist,Technical Support Specialist,"Technical troubleshooting Customer support tools (e.g., Zendesk, Freshdesk) Communication skills Problem-solving and critical thinking Ticket management Knowledge base creation"
1310,Process Engineer,Chemical Engineer,Chemical engineering Process design Chemical reactions Safety protocols Laboratory techniques Problem-solving skills

In [17]:
# -----------------------------
# Saving reduced subset for Notebook 9
# -----------------------------
DEMO_SUBSET_PARQUET = DATA_PROCESSED / "demo_jobs_subset.parquet"

demo_subset.to_parquet(DEMO_SUBSET_PARQUET, index=False)

print("Saved subset to:", DEMO_SUBSET_PARQUET)

Saved subset to: C:\Users\COMPUTER CARE\aeej1\JobPlatform\data\processed\demo_jobs_subset.parquet

In [18]:
# -----------------------------
# Reload saved parquet to verify schema
# -----------------------------
check_subset = pd.read_parquet(DEMO_SUBSET_PARQUET)

print("Saved parquet shape:", check_subset.shape)
print("Saved parquet columns:")
print(check_subset.columns.tolist())

display(check_subset[["job_title", "role", "skills"]].head(10))

Saved parquet shape: (5000, 17)
Saved parquet columns:
['job_id', 'experience', 'qualifications', 'location', 'salary_range', 'country', 'work_type', 'job_posting_date', 'job_title', 'role', 'job_portal', 'job_description', 'benefits', 'skills', 'responsibilities', 'company_name', 'company_profile']

,job_title,role,skills
0,Java Developer,Java Software Engineer,"Java programming Java frameworks (e.g., Spring) Object-oriented design Code debugging Software development Problem-solving skills"
1,Architectural Designer,Architectural Drafter,Architectural drafting AutoCAD 2D and 3D modeling Blueprint reading Building codes Collaboration with architects Detail-oriented
2,Business Analyst,Healthcare Business Analyst,Healthcare industry knowledge Health data analysis HIPAA regulations EMR systems
3,QA Analyst,Software QA Tester,"Software quality assurance Test planning Test case design Test execution Defect tracking Test automation (e.g., Selenium)"
4,Sales Consultant,Sales Trainer,Sales training Sales coaching Training program development Sales techniques Product knowledge Presentation skills
5,Systems Engineer,Systems Integration Specialist,Systems integration Integration architecture Data mapping Middleware technologies API integration System testing Troubleshooting
6,Environmental Consultant,Sustainability Consultant,Sustainability consulting Sustainability assessments Sustainable practices Green building standards Environmental policies Client communication
7,Web Developer,Frontend Web Developer,"HTML, CSS, JavaScript Frontend frameworks (e.g., React, Angular) User experience (UX)"
8,Customer Support Specialist,Technical Support Specialist,"Technical troubleshooting Customer support tools (e.g., Zendesk, Freshdesk) Communication skills Problem-solving and critical thinking Ticket management Knowledge base creation"
9,Process Engineer,Chemical Engineer,Chemical engineering Process design Chemical reactions Safety protocols Laboratory techniques Problem-solving skills

## Demo Subset Creation Summary

This notebook creates a reduced job postings subset for the final product demo. Only the fields needed for recommendation and frontend presentation are retained. The pipeline preserves both `job_title` and `role` as separate fields, rather than collapsing one into the other.

Rows with weak or incomplete text are removed, obvious duplicates are filtered out, and the final subset is balanced across role labels where possible. The resulting dataset is saved for downstream processing and embedding generation.resentation.t.head(3))sentation.